name: automated_test
on:
  push:
    paths:
      - '.github/workflows/**'
      - 'tests/**'
      - 'package-lock.json'
      - 'package.json'
      - 'playwright.config.ts'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'tests/**'
      - 'package-lock.json'
      - 'package.json'
      - 'playwright.config.ts'
  #schedule:
  #  - cron: '0 22 * * *'  # 22:00 UTC = 7:00 JST
  workflow_dispatch:      # for manual testing

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      #matrix:
      #  browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Automated tests
        run: npx playwright test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Playwright report
          path: playwright-report/
          retention-days: 30

      - name: Setup Github Pages
        uses: actions/configure-pages@v5
        if: always() && github.ref == 'refs/heads/main'

      - name: Upload Artifacts to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        if: always() && github.ref == 'refs/heads/main'
        with:
          path: ./playwright-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: always() && github.ref == 'refs/heads/main'
